### ISSUE TITLE
Error handling response: SyntaxError: Unexpected token u in JSON at position 0

### ISSUE THREAD

**Issue by santosh** [nashvail/Chronus#5]
While loading the extension, I'm getting this error: 

![image](https://user-images.githubusercontent.com/1515991/55728710-3e347280-5a32-11e9-9713-9b35c05aa511.png)

When I expand that, I get these details:

### Context

    _generated_background_page.html

### Stack Trace

    js/background.js:69 (anonymous function)

```
// Do all the startup tasks
function startUp() {
    //Initialize the totalTimeOnWebsites variable to the data gained from the local storage of the user
    chrome.storage.local.get(null, function(result){
        totalTimeOnWebsites = result["timeData" + numDaysSinceUTC()];
        today = result["today"];
        websitesToTrack = JSON.parse(result.trackData);
```

**Comment by ghost** [comment]
@santosh  just remove the json.parse function.

**Comment by ezio-ac** [comment]
please provide the steps to resolve this.
I am unable to get it working
thanks

**Comment by ezio-ac** [comment]
@santosh 
@nashvail

**Comment by santosh** [comment]
@ezio-ac I'm not sure how I resolved it. 
I am in no longer in touch with Chronus for a while.
